events {}

http {
    server {
        listen 80;

        location  /api/customers {
            auth_request /auth-verify;
            proxy_pass http://customer-service:3001/customers;
        }

        location  /api/accounts {
            auth_request /auth-verify;
            proxy_pass http://account-service:3002/accounts;
        }

        location  /api/payments {
            auth_request /auth-verify;
            proxy_pass http://payment-service:3003/payments;
        }

        location  /api/auth {
            
            proxy_pass http://auth-service:3004/auth;
        }

        location = /api/health {
            
            proxy_pass http://gateway-health:3005/health;
        }

        location = /auth-verify {
            internal;
        
            proxy_pass http://auth-service:3004/auth/verify;
        
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
        
            proxy_set_header Authorization $http_authorization;
        }   

    }
}
