events {}

http {
    server {
        listen 80;

        location  /api/customers {
            proxy_pass http://customer-service:3001/customers;
        }

        location  /api/accounts {
            proxy_pass http://account-service:3002/accounts;
        }

        location  /api/payments {
            proxy_pass http://payment-service:3003/payments;
        }

        location  /api/auth {
            proxy_pass http://auth-service:3004/auth;
        }

        location = /api/health {
            proxy_pass http://gateway-health:3005/health;
        }

    }
}
